### ISSUE TITLE
Cannot register tunnel

### ISSUE THREAD

**Issue by mholt** [cloudflare/cloudflare-warp#2]
While doing some refactoring in a branch, I finally got it to a running state but now I have this error. I checked out the original branch (master) just to be sure, and the error still appears (I added a single print line to show the error message):

```
$ go build && ./cloudflare-warp --hostname my.hostname --hello-world --no-autoupdate
INFO[0000] Proxying tunnel requests to https://127.0.0.1:53287 
INFO[0000] Starting Hello World server at 127.0.0.1:53287 
INFO[0000] Starting metrics server                       addr="127.0.0.1:53288"
ERRO[0000] handle return: received return for unknown question id=0  subsystem=rpc-transport
INFO[0000] Connected to LAX                             
pogs: insert @0xc793e50592935b4a: can't insert into pogs.RegistrationOptions: pogs.RegistrationOptions has unknown field PoolName, maps to poolName
ERRO[0000] Cannot register                              
INFO[0000] Retrying in 1s seconds
```

Does this have something to do with an inconsistency between the client and the backend maybe? I actually have no idea.

**Comment by mholt** [comment]
Commenting out the fields `PoolName` and `IsAutoupdated` in `pogs.RegistrationOptions` struct resolves the problem. I just don't comprehend at what cost. :) It's working now, with that change. Will leave open for advisement.

**Comment by chungthuang** [comment]
Hi mholt, thanks for reporting the issue! We will tunnelrpc.capnp.go.

**Comment by chungthuang** [comment]
tunnelrpc.capnp.go has been updated. You shouldn't need to comment out `PoolName` and `IsAutoupdated` in `pogs.RegistrationOptions` anymore.
